name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - 'v*'  # Runs only when a tag starting with "v" (e.g., v1.0.0) is pushed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Extract the Git tag name
      - name: Extract Tag Name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Step 4: Set image name
      - name: Set Docker Image Name
        run: echo "IMAGE_NAME=ghcr.io/fred-maussion/demo_ecs_java_logging" >> $GITHUB_ENV

      # Step 5: Build the Docker image with the tag
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$TAG_NAME .

      # Step 6: Push the Docker image to GHCR
      - name: Push Docker Image to GHCR
        run: |
          docker push $IMAGE_NAME:$TAG_NAME