name: Build and Push Java App on Tag

on:
  push:
    tags:
      - 'v*'  # Runs only when a tag starting with "v" (e.g., v1.0.0) is pushed

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Java 17 and enable Maven caching
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven

      # Step 3: Build with Maven (Skipping tests if needed)
      - name: Build with Maven Wrapper
        run: ./mvnw -B package -DskipTests
  
      # Step 4: Upload the JAR as an artifact
      - name: Upload JAR as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: elastic-petclinic-jar
          path: target/*.jar
          retention-days: 7
